version: '3.8'

services:
  # Start MongoDB first since it's needed by all services
  ai-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  # Database initialization service (Runs before backend)
  db-init:
    image: ${ACR_LOGIN_SERVER}/db-init:${IMAGE_TAG}
    depends_on:
      - ai-mongo
    command:
      - "python3"
      - "/scripts/populate_memes.py"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ai-mongo
      MONGO_DB_NAME: ethics_db

  # AI Ethical Work Backend API Service
  ai-backend:
    image: ${ACR_LOGIN_SERVER}/backend:${IMAGE_TAG}
    depends_on:
      - ai-mongo
      - db-init
    ports:
      - "5000:5000"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ai-mongo
      MONGO_DB_NAME: ethics_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      XAI_API_KEY: ${XAI_API_KEY}

  # AI Ethical Work Frontend Service (Nginx)
  ai-frontend:
    image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
    depends_on:
      - ai-backend
    ports:
      - "80:80" 