version: '3.8'

services:
  # Start MongoDB first since it's needed by all services
  ai-mongo:
    image: mongo:latest
    container_name: ai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/ethics_db --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - ai-network

  # AI Ethical Work Backend API Service
  ai-backend:
    image: ethicsdashacr.azurecr.io/backend:latest
    container_name: ai-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@ai-mongo:27017/ethics_db?authSource=admin
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@ai-mongo:27017/ethics_db?authSource=admin
      - MONGO_DB_NAME=ethics_db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      ai-mongo:
        condition: service_healthy
    networks:
      - ai-network

  # AI Ethical Work Frontend Service (Nginx)
  ai-frontend:
    image: ethicsdashacr.azurecr.io/frontend:latest
    container_name: ai-frontend
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      ai-backend:
        condition: service_healthy
    networks:
      - ai-network

  # Database initialization service - configured as a non-essential init container
  # Using 'init: true' signals this is an initialization container that can exit
  db-init:
    image: ethicsdashacr.azurecr.io/db-init:latest
    container_name: ai-db-init
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@ai-mongo:27017/ethics_db?authSource=admin
      - MONGO_DB_NAME=ethics_db
    # Keep the container running after the script finishes
    command: >
      sh -c "python3 /scripts/populate_memes.py && echo 'Initialization complete. Keeping container alive...' && tail -f /dev/null"
    restart: "no"
    depends_on:
      ai-mongo:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: none
    labels:
      - "com.microsoft.azure.app.type=init"
    networks:
      - ai-network

volumes:
  mongodb_data:

# Network definition
networks:
  ai-network:
    #driver: bridge  # Removed explicit driver
    #name: ethicsdash-network # Removed explicit name 