version: '3.8'

services:
  # Fast API Backend
  ai-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load local environment variables into container
    environment:
      - MONGODB_URI=mongodb://ai-mongo:27017/ethics_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Ethical Ontology Blockchain Configuration
      - ETHICAL_ONTOLOGY_NETWORK_ID=ethical-ontology-local
      - ETHICAL_ONTOLOGY_BLOCKCHAIN_ENDPOINT=http://ethical-ontology-blockchain:8545
      - ETHICAL_CONTRACTS_AUTO_DEPLOY=true
      # PVB Blockchain Configuration
      - WEB3_PROVIDER_URL=http://ganache:8545
      - REGISTRY_CONTRACT_ADDRESS=${REGISTRY_CONTRACT_ADDRESS}
      - SUBMISSION_CONTRACT_ADDRESS=${SUBMISSION_CONTRACT_ADDRESS}
      - BLOCKCHAIN_PRIVATE_KEY=${BLOCKCHAIN_PRIVATE_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      ai-mongo:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./documents:/app/documents
    networks:
      - ai-network

  # React Frontend
  ai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      ai-backend:
        condition: service_healthy
    networks:
      - ai-network

  # MongoDB Database
  ai-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/ethics_db --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - ai-network

  # DB Initialization Service
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.db-init
    environment:
      - MONGO_URI=mongodb://ai-mongo:27017/ethics_db
    command: ["python", "/scripts/populate_memes.py", "/app/documents/memes.json"]
    restart: "no"
    depends_on:
      ai-mongo:
        condition: service_healthy
    volumes:
      - ./documents:/app/documents
    networks:
      - ai-network

  # Ethical Ontology Blockchain Service
  ethical-ontology-blockchain:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Reuse backend dockerfile with blockchain dependencies
    ports:
      - "8545:8545"  # Main blockchain node port
    environment:
      - NODE_ID=validator_1
      - NODE_PORT=8545
      - IS_VALIDATOR=true
      - MINING_ENABLED=true
      - NETWORK_ID=ethical-ontology-local
      - MAX_CONNECTIONS=20
      - ETHICAL_ONTOLOGY_NETWORK_ID=ethical-ontology-local
      - ETHICAL_ONTOLOGY_BLOCK_TIME_SECONDS=10
      - ETHICAL_CONTRACTS_DEONTIC_RULES_AUTO_DEPLOY=true
      - ETHICAL_CONTRACTS_VIRTUE_REPUTATION_AUTO_DEPLOY=true
      - ETHICAL_CONTRACTS_TELEOLOGICAL_OUTCOMES_AUTO_DEPLOY=true
    command: ["python", "/app/scripts/ethical_ontology_deploy.py", "--network", "ethical-ontology-local"]
    restart: unless-stopped
    volumes:
      - ./ethical_ontology:/app/ethical_ontology
      - ./scripts:/app/scripts
      - ./documents:/app/documents
      - blockchain_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app'); from ethical_ontology.blockchain.core import EthicalOntologyBlockchain; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - ai-network

  # Additional Ethical Ontology Blockchain Peer (for testing consensus)
  ethical-ontology-peer:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8546:8546"
    environment:
      - NODE_ID=peer_1
      - NODE_PORT=8546
      - IS_VALIDATOR=true
      - MINING_ENABLED=true
      - NETWORK_ID=ethical-ontology-local
      - MAX_CONNECTIONS=10
      - ETHICAL_ONTOLOGY_NETWORK_ID=ethical-ontology-local
    command: ["python", "-c", "import time; print('Peer node waiting for validator...'); time.sleep(30); print('Peer node ready')"]
    restart: unless-stopped
    depends_on:
      ethical-ontology-blockchain:
        condition: service_healthy
    volumes:
      - ./ethical_ontology:/app/ethical_ontology
      - peer_blockchain_data:/app/data
    networks:
      - ai-network

  # Ganache Blockchain for PVB Development
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "7545:8545"  # Map container port 8545 to host port 7545
    command: >
      ganache
      --host 0.0.0.0
      --port 8545
      --accounts 10
      --deterministic
      --mnemonic "ethics dashboard physical verification blockchain development test mnemonic phrase"
      --networkId 1337
      --gasLimit 10000000
      --gasPrice 20000000000
      --defaultBalanceEther 100
      --blockTime 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - ai-network

# Additional services can be added here
# For example, a service for model fine-tuning, etc.

# Volume definitions
volumes:
  mongodb_data:
  blockchain_data:
  peer_blockchain_data:

# Network definition
networks:
  ai-network:
    driver: bridge

# You can add other services (like a database) here
# volumes:
#   db-data:

# Uncomment and configure these variables in .env file
# ACR_REGISTRY=yourregistry.azurecr.io
# ACR_USERNAME=yourusername
# ACR_PASSWORD=yourpassword 