version: '3.8'

services:
  # Fast API Backend
  ai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://ai-mongo:27017/ethics_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - ai-mongo
    volumes:
      - ./backend:/app/backend
      - ./documents:/app/documents
    networks:
      - ai-network

  # React Frontend
  ai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - ai-backend
    networks:
      - ai-network

  # MongoDB Database
  ai-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-network

  # DB Initialization Service
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.db-init
    environment:
      - MONGO_URI=mongodb://ai-mongo:27017/ethics_db
    depends_on:
      - ai-mongo
    volumes:
      - ./documents:/app/documents
    networks:
      - ai-network

# Additional services can be added here
# For example, a service for model fine-tuning, etc.

# Volume definitions
volumes:
  mongodb_data:

# Network definition
networks:
  ai-network:
    driver: bridge

# You can add other services (like a database) here
# volumes:
#   db-data:

# Uncomment and configure these variables in .env file
# ACR_REGISTRY=yourregistry.azurecr.io
# ACR_USERNAME=yourusername
# ACR_PASSWORD=yourpassword 