version: '3.4'

services:
  # AI Ethical Work Backend API Service
  ai-backend:
    image: ${ACR_REGISTRY:-ethicsdashacr.azurecr.io}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://ai-mongo:27017/ethics_db
    depends_on:
      - ai-mongo

  # AI Ethical Work Frontend Service (Nginx)
  ai-frontend:
    image: ${ACR_REGISTRY:-ethicsdashacr.azurecr.io}/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - ai-backend

  # AI Ethical Work MongoDB Service
  ai-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Database initialization service
  db-init:
    image: ${ACR_REGISTRY:-ethicsdashacr.azurecr.io}/db-init:latest
    depends_on:
      - ai-mongo
    environment:
      - MONGO_URI=mongodb://ai-mongo:27017/ethics_db
    command: ["python", "/scripts/populate_memes.py", "/documents/memes.json"]

volumes:
  mongo_data:

# You can add other services (like a database) here
# volumes:
#   db-data:

# networks:
#   my-network:

# Uncomment and configure these variables in .env file
# ACR_REGISTRY=yourregistry.azurecr.io
# ACR_USERNAME=yourusername
# ACR_PASSWORD=yourpassword 