version: '3.8' # Specify docker-compose version

services:
  # Backend API service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ethical-review-backend
    env_file:
      # Reference .env file in the parent directory (project root)
      - ../../.env
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      # Mount the local context directory into the container for log persistence
      # This ensures prompts.txt survives container restarts/removals
      - ../../Context:/app/context
    # Automatically restart the container unless it is manually stopped
    restart: unless-stopped
    # Basic healthcheck to see if the web server is responding
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s # Give the container time to start before checking
    # Optional: Add restart policy if needed
    # restart: unless-stopped 
    depends_on:
      - mongo # Add dependency on mongo service

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ethical-review-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 

  # MongoDB Service (for ethical memes library)
  mongo:
    image: mongo:latest # Use the official MongoDB image
    container_name: ethical-review-mongodb
    ports:
      - "27018:27017" # Expose default MongoDB port to host port 27018
    volumes:
      - mongo_data:/data/db # Persist database data using a named volume
      # Mount the initialization script
      - ./mongo-init/improved-meme-import.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Mount improved script as read-only
    environment: {} # Provide an empty mapping to satisfy the schema
      # Optional: Set root user/password if needed, but often not required for local dev
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

# Named volume for MongoDB data persistence
volumes:
  mongo_data: null # Keep this as null (or {} - both should be valid here) 