# .github/workflows/build_push_acr.yml

name: Build and Push Docker Images to ACR

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

env:
  # Set your ACR name here or preferably store it as a GitHub Secret (e.g., ACR_REGISTRY)
  # and reference it like ${{ secrets.ACR_REGISTRY }}
  ACR_REGISTRY_NAME: "ethicsdashacr" # Replace with your ACR name (e.g., ethicsdashacr)
  # Define image names based on your services
  IMAGE_NAME_APP: "ethics-dash-app"
  IMAGE_NAME_BACKEND: "ai-ethical-review-backend"
  IMAGE_NAME_FRONTEND: "ai-ethical-review-frontend"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      # Required for Azure login using OIDC (GitHub App/Federated Credentials)
      id-token: write
      contents: read # Needed to check out the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure using GitHub App
      uses: azure/login@v2
      with:
        # Credentials for your GitHub App's Service Principal stored as GitHub secrets
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # enable-AzPSSession: true # Optional: If you need Azure PowerShell later

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        # Uses the token from the previous azure/login step
        login-server: ${{ env.ACR_REGISTRY_NAME }}.azurecr.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- Build and Push 'app' service ---
    - name: Build and push 'app' image
      uses: docker/build-push-action@v5
      with:
        context: . # Root context for the main Dockerfile
        file: ./Dockerfile # Path relative to root
        push: true
        tags: |
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_APP }}:latest
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_APP }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --- Build and Push 'ai-backend' service ---
    - name: Build and push 'ai-backend' image
      uses: docker/build-push-action@v5
      with:
        context: ./ethics_dash/AI_Ethical_Work # Context for this service
        # IMPORTANT: Dockerfile path is relative to REPO ROOT, not context
        file: ./ethics_dash/AI_Ethical_Work/backend/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:latest
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --- Build and Push 'ai-frontend' service ---
    - name: Build and push 'ai-frontend' image
      uses: docker/build-push-action@v5
      with:
        context: ./ethics_dash/AI_Ethical_Work # Context for this service
        # IMPORTANT: Dockerfile path is relative to REPO ROOT, not context
        file: ./ethics_dash/AI_Ethical_Work/frontend/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest
          ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Optional: Logout from ACR and Azure
    # Add steps here if needed, though often not necessary for runner cleanup 