# Workflow for building, deploying, and troubleshooting the Ethics Dashboard
name: Build and Deploy to Azure Web App

on:
  workflow_dispatch: # Manual trigger only

env:
  AZURE_WEBAPP_NAME: ethicsdash-cicd-app
  ACR_NAME: ethicsdashacr
  ACR_LOGIN_SERVER: ethicsdashacr.azurecr.io
  RESOURCE_GROUP: ethicsdash-rg
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated version
        with:
          fetch-depth: 0
          repository: jbcupps/Ethics_Dash

      - name: Login to Azure via OIDC
        uses: azure/login@v2 # Updated version
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Kept version, seems current

      - name: Build and push backend image
        uses: docker/build-push-action@v6 # Updated version
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/backend:${{ env.IMAGE_TAG }}
            ${{ env.ACR_LOGIN_SERVER }}/backend:latest
          platforms: linux/amd64 # Added platform
          build-args: |
            BUILDTIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Build and push frontend image
        uses: docker/build-push-action@v6 # Updated version
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
            ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          platforms: linux/amd64 # Added platform
          build-args: |
            BUILDTIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Build and push db-init image
        uses: docker/build-push-action@v6 # Updated version
        with:
          context: .
          file: Dockerfile.db-init
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/db-init:${{ env.IMAGE_TAG }}
            ${{ env.ACR_LOGIN_SERVER }}/db-init:latest
          platforms: linux/amd64 # Added platform

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated version
        with:
          fetch-depth: 0

      - name: Login to Azure via OIDC
        uses: azure/login@v2 # Updated version
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Get MongoDB Username from Azure Key Vault (for deploy job)
        id: get-mongo-username-deploy
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            secret_value=$(az keyvault secret show --vault-name "ethicsdashkv" --name "mongo-db-username" --query value -o tsv)
            echo "::set-output name=secret::$secret_value"

      - name: Get MongoDB Password from Azure Key Vault (for deploy job)
        id: get-mongo-password-deploy
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            secret_value=$(az keyvault secret show --vault-name "ethicsdashkv" --name "mongo-db-password" --query value -o tsv)
            echo "::set-output name=secret::$secret_value"

      - name: Enable container logging
        run: |
          az webapp log config --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --docker-container-logging filesystem

      - name: Configure App Settings
        run: |
          az webapp config appsettings set --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --settings \
            ACR_LOGIN_SERVER="${{ env.ACR_LOGIN_SERVER }}" \
            IMAGE_TAG="${{ env.IMAGE_TAG }}" \
            MONGO_USERNAME="${{ steps.get-mongo-username-deploy.outputs.secret }}" \
            MONGO_PASSWORD="${{ steps.get-mongo-password-deploy.outputs.secret }}" \
            NODE_ENV="production" \
            LOG_LEVEL="info" \
            API_VERSION="v1" \
            WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
            BACKEND_HOST="ai-backend" \
            BACKEND_PORT="5000" \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            XAI_API_KEY="${{ secrets.XAI_API_KEY }}" \
            DEFAULT_LLM_MODEL="gpt-4" \
            ANALYSIS_LLM_MODEL="claude-3-opus-20240229" \
            OPENAI_API_ENDPOINT="https://api.openai.com/v1" \
            ANTHROPIC_API_ENDPOINT="https://api.anthropic.com" \
            GEMINI_API_ENDPOINT="https://generativelanguage.googleapis.com" \
            XAI_API_ENDPOINT="https://api.grok.x"

      - name: Deploy multi-container Web App using Docker Compose
        uses: azure/cli@v1  # Use Azure CLI action for multi-container deployment
        with:
          azcliversion: latest
          inlineScript: |
            az webapp config container set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --multicontainer-config-type compose \
              --multicontainer-config-file docker-compose.azure.yml

      - name: Wait for Web App to start
        run: |
          echo "Waiting for Azure Web App to start..."
          for i in {1..30}; do
            state=$(az webapp show --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --query state -o tsv)
            echo "Current state: $state"
            if [ "$state" = "Running" ]; then
              echo "Web App is running"
              exit 0
            fi
            sleep 10
          done
          echo "Web App did not start within expected time"
          exit 1

      - name: Download and display container logs
        run: |
          az webapp log download \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --log-file logs.zip
          unzip logs.zip -d logs
          echo "==== Last 200 lines of logs ===="
          find logs -type f -exec tail -n 200 {} \; || true

      - name: Display Application URL
        run: |
          echo "Front-end is available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"

      - name: Azure Logout # Added logout step
        run: az logout
        if: always()